// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DorkNet.Server.Data;

#nullable disable

namespace DorkNet.Server.Migrations
{
    [DbContext(typeof(DorkNetDbContext))]
    [Migration("20260508092637_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DorkNet.Server.Data.Entities.AvatarEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquippedItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("DorkNet.Server.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanReceiveInvites")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsJunior")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPlatform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPlatformId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileImageName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Reputation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DorkNet.Server.Data.Entities.PlayerSettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Key")
                        .IsUnique();

                    b.ToTable("PlayerSettings");
                });

            modelBuilder.Entity("DorkNet.Server.Data.Entities.RelationshipEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("RequesterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId", "TargetId")
                        .IsUnique();

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("DorkNet.Server.Data.Entities.RoomBookmarkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "RoomId")
                        .IsUnique();

                    b.ToTable("RoomBookmarks");
                });

            modelBuilder.Entity("DorkNet.Server.Data.Entities.RoomEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accessibility")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowsJuniors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheerCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloningAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatorPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomRoomWarning")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisableMicAutoMute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HotScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAGRoom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDormRoom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationReplicationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("RoomWarningMask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsLevelVoting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsMobile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsScreens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsTeleportVR")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsVRLow")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsWalkVR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsCsv")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatorPlayerId");

                    b.HasIndex("HotScore");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DorkNet.Server.Data.Entities.AvatarEntity", b =>
                {
                    b.HasOne("DorkNet.Server.Data.Entities.PlayerEntity", "Player")
                        .WithOne("Avatar")
                        .HasForeignKey("DorkNet.Server.Data.Entities.AvatarEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DorkNet.Server.Data.Entities.PlayerSettingEntity", b =>
                {
                    b.HasOne("DorkNet.Server.Data.Entities.PlayerEntity", "Player")
                        .WithMany("Settings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DorkNet.Server.Data.Entities.RelationshipEntity", b =>
                {
                    b.HasOne("DorkNet.Server.Data.Entities.PlayerEntity", "Requester")
                        .WithMany("Relationships")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("DorkNet.Server.Data.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Avatar");

                    b.Navigation("Relationships");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
