namespace DorkNet.Server.Data.Entities;

/// <summary>
/// An admin-issued, single-use signup code (Discord-invite style). While
/// the server has signups disabled, the only way to mint a new account is
/// to redeem one of these on the public site's <c>/join</c> page. Each
/// code carries a free-text <see cref="Descriptor"/> so admins can track
/// who they handed it to, an optional <see cref="ExpiresAt"/>, and the
/// redemption result (<see cref="RedeemedByPlayerId"/> /
/// <see cref="RedeemedAt"/>). Codes can be revoked before use.
/// </summary>
public class SignupCodeEntity
{
    public long Id { get; set; }

    /// <summary>The opaque code string the player types on /join.
    /// Uppercase, hyphenated, unambiguous alphabet (no 0/O/1/I).</summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>Free-text note for the admin — "who is this for". Shown
    /// only in the admin panel, never to the redeemer.</summary>
    public string Descriptor { get; set; } = string.Empty;

    /// <summary>Player id of the admin who generated the code (0 if
    /// generated by a system/CLI path).</summary>
    public long CreatedByPlayerId { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Optional hard expiry. Null = never expires.</summary>
    public DateTime? ExpiresAt { get; set; }

    /// <summary>Set once the code is redeemed; null while unused.</summary>
    public long? RedeemedByPlayerId { get; set; }
    public DateTime? RedeemedAt { get; set; }

    /// <summary>Admin kill switch — a revoked code can never be redeemed,
    /// even if otherwise valid.</summary>
    public bool Revoked { get; set; }
}
